import type { Plant } from '@/lib/types'

export const DEMO_HOUSEHOLD_ID = 'demo-momma-ds-garden'

export const demoPlants: Plant[] = [
  {
    id: 'demo-tomato',
    name: 'Cherokee Purple Tomato',
    scientific_name: 'Solanum lycopersicum',
    description: 'Heirloom tomato grown for rich flavor, big slicers, and summer bragging rights.',
    image_url: null,
    category: 'vegetable',
    sunlight_needs: 'full_sun',
    water_needs: 'moderate',
    difficulty: 'moderate',
    growing_season: 'Warm season',
    days_to_harvest: 80,
    spacing_inches: 24,
    min_temp_f: 55,
    max_temp_f: 90,
    care_tips: 'Stake early, water deeply, mulch heavily, and prune lower leaves for airflow.',
  },
  {
    id: 'demo-basil',
    name: 'Genovese Basil',
    scientific_name: 'Ocimum basilicum',
    description: 'Fragrant basil for pesto, tomatoes, and kitchen-counter victory laps.',
    image_url: null,
    category: 'herb',
    sunlight_needs: 'full_sun',
    water_needs: 'moderate',
    difficulty: 'easy',
    growing_season: 'Warm season',
    days_to_harvest: 30,
    spacing_inches: 12,
    min_temp_f: 50,
    max_temp_f: 90,
    care_tips: 'Pinch flowers quickly and harvest often to keep leaves tender.',
  },
  {
    id: 'demo-zinnia',
    name: 'Cut-and-Come-Again Zinnia',
    scientific_name: 'Zinnia elegans',
    description: 'Bright pollinator magnet that makes the garden look like it dressed up for company.',
    image_url: null,
    category: 'flower',
    sunlight_needs: 'full_sun',
    water_needs: 'low',
    difficulty: 'easy',
    growing_season: 'Warm season',
    days_to_harvest: 60,
    spacing_inches: 12,
    min_temp_f: 60,
    max_temp_f: 95,
    care_tips: 'Deadhead regularly for more blooms and better airflow.',
  },
  {
    id: 'demo-cucumber',
    name: 'Marketmore Cucumber',
    scientific_name: 'Cucumis sativus',
    description: 'Classic slicing cucumber for trellis growing and snack raids.',
    image_url: null,
    category: 'vegetable',
    sunlight_needs: 'full_sun',
    water_needs: 'high',
    difficulty: 'moderate',
    growing_season: 'Warm season',
    days_to_harvest: 60,
    spacing_inches: 18,
    min_temp_f: 60,
    max_temp_f: 90,
    care_tips: 'Trellis to save space and pick often before fruits get oversized.',
  },
]
